language: node_js
env:
    global:
        - CC_TEST_REPORTER_ID=ad66ab888d21296567710f4f77a75fb314935229c7010313e65bccc642e784e9
        - NODE_ENV=test
matrix:
    include:
    #   - node_js: '10'
    - node_js: '12'
cache:
    directories: node_modules

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - yarn test
after_success:
    - yarn coverage
after_script:
    - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
